# Copyright (c) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");

import("//build/ohos.gni")

ohos_executable("sleip_netshare_stage3") {
  sources = [
    "../../services/networksharemanager/src/router_advertisement_daemon.cpp",
    "../../services/networksharemanager/src/router_advertisement_params.cpp",
    "sleip_ipv6_config.cpp",
    "sleip_system_network.cpp",
    "sleip_netshare_stage3.c",
  ]
  include_dirs = [
    "../../interfaces/innerkits/include",
    "../../services/networksharemanager/include",
  ]
  deps = [ "../../interfaces/innerkits/netshareclient:net_tether_manager_if" ]
  external_deps = [
    "netmanager_base:net_conn_manager_if",
    "access_token:libaccesstoken_sdk",
    "access_token:libnativetoken",
    "access_token:libtoken_setproc",
    "c_utils:utils",
    "ffrt:libffrt",
    "hilog:libhilog",
    "netmanager_base:net_manager_common",
  ]
  subsystem_name = "communication"
  part_name = "netmanager_ext"
  install_enable = true
}
